services:
  postgres:
    container_name: postgres-geo
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: geo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
        
volumes:
  postgres-data:
